### ISSUE TITLE
Add preserve_host_header argument to aws_lb

### ISSUE THREAD

**Issue by siarheirdn** [cloudposse/terraform-aws-alb#123]
## Add preserve_host_header argument to aws_lb

https://github.com/hashicorp/terraform-provider-aws/pull/26056
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#preserve_host_header

## Expected Behavior

ALB created wth preserve_host_header option

**Comment by tbpoetke** [comment]
I fixed it already locally, will do a PR soon
