### ISSUE TITLE
support terraform 0.12

### ISSUE THREAD

**Issue by 0markill** [cloudposse/terraform-aws-alb#18]
on init with the new terraform version i receive the following error:

> Error: Unsupported Terraform Core version
> 
> This configuration does not support Terraform version 0.12.1. To proceed,
> either choose another supported Terraform version or update the root module's
> version constraint. Version constraints are normally set for good reason, so
> updating the constraint may lead to other errors or unexpected behavior.

is there any plan to support version 0.12 and above?

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-alb/releases/tag/0.7.0
