### ISSUE TITLE
Ability to configure a redirect to an arbitrary URL

### ISSUE THREAD

**Issue by vonZeppelin** [cloudposse/terraform-aws-alb#184]
### Describe the Feature

Support configuring a redirection to an arbitrary URL as the default action of an ALB.

### Expected Behavior

ALB supports configuring a redirection to an arbitrary URL and to a modified URL, but only HTTP -> HTTPS redirection can be set with this module currently.

### Use Case

For example, SaaS app's ALB default action can be a redirection to a company's website.

### Describe Ideal Solution

The module has an input variable(s) to configure URL redirection.

### Alternatives Considered

A fixed HTML response with `<meta http-equiv="refresh" content="0;URL='https://acme.com'"` tag can be used to redirect to an arbitrary URL for cases when ALB's main client is a web browser.

**Comment by oycyc** [comment]
resolved in here  https://github.com/cloudposse/terraform-aws-alb/pull/187
