### ISSUE TITLE
How to create a TDD approach to the resources

### ISSUE THREAD

**Issue by rifaterdemsahin** [cloudposse/terraform-aws-alb#25]
We need to make sure the terraform scripts we use are working.
ttps://github.com/cloudposse/terraform-aws-alb/blob/master/main.tf

how can we know this one working before pulling it to our repo ?

**Comment by techfishio** [comment]
Easiest is to set up a "test" aws account and run the module against it. Almost all of the Infrastructure as Code and configuration management tools I've used suffer from endless chicken and egg scenarios. At some point, you just have to set up a mock infrastructure to test it against.

Albeit much more involved, you could also try: https://newcontext-oss.github.io/kitchen-terraform
