### ISSUE TITLE
Feature Req - Stickness Enable/Disable Support

### ISSUE THREAD

**Issue by francobontorin** [cloudposse/terraform-aws-alb#35]
I haven't figured out a way to enable/disable sitckness sessions on the ALB. It looks by default you always set it to true with 1 day of expiration.

Thanks

**Comment by deadlysyn** [comment]
Hi @francobontorin I have deployed ALB using this module and see stickiness disabled by default. Looking at module's target group stanza there is no sticky config.

I will work on a PR to make this configurable and submit for feedback.
