### ISSUE TITLE
Limit hit when passing CloudFront CIDRs to ALB security group

### ISSUE THREAD

**Issue by mihaiplesa** [cloudposse/terraform-aws-alb#84]
## Describe the Feature

Apply fails since there are over 100 CIDRs to set on a single security group as it is now.

## Expected Behavior

Rules should be split in groups of 50 let's say and multiple security groups created and assigned then to the ALB.

## Use Case

Restrict ALB ingress to CloudFront IPs.

## Describe Ideal Solution

Create multiple security groups based on limit of 60 rules per security group.

## Alternatives Considered

Create separate security groups based on `chunklist(data.aws_ip_ranges.cloudfront.cidr_blocks, 50)` and pass them as list to `security_group_ids`.

**Comment by nitrocode** [comment]
@mihaiplesa I think you can get around this by setting the following inputs to manage your security group outside of this module

```hcl
  security_group_enabled = false
  security_group_ids     = ["sg-1234567890"]
```
