### ISSUE TITLE
Orphaned Target Group "default"

### ISSUE THREAD

**Issue by welderpb** [cloudposse/terraform-aws-alb#94]
Orphaned target group(default) is created when i use "fixed response" for both listeners, http and https..

**Comment by nitrocode** [comment]
Sounds like we need to remove the target group if both the `listener_http_fixed_response` and `listener_https_fixed_response` are set.

So change this

```hcl
  count                = module.this.enabled ? 1 : 0
```

to this

```hcl
  count                = module.this.enabled && listener_http_fixed_response != null && listener_https_fixed_response != null ? 1 : 0
```

Is that right @welderpb ?

**Comment by welderpb** [comment]
> Sounds like we need to remove the target group if both the `listener_http_fixed_response` and `listener_https_fixed_response` are set.
> 
> So change this
> 
> ```terraform
>   count                = module.this.enabled ? 1 : 0
> ```
> 
> to this
> 
> ```terraform
>   count                = module.this.enabled && listener_http_fixed_response == null && listener_https_fixed_response == null ? 1 : 0
> ```
> 
> Is that right @welderpb ?

Yes, you right..
